#!/usr/bin/env python3
"""Generate Go source files for remaining lab cases."""
import os

def write_file(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {path}")

# tx_case.go
write_file("pkg/cases/tx_case.go", [
    'package cases',
    '',
    'import (',
    '\t"database/sql"',
    '\t"encoding/json"',
    '\t"log"',
    '\t"net/http"',
    '\t"time"',
    '',
    '\t"github.com/infobloxopen/architecture-workshops2/pkg/depclient"',
    ')',
    '',
    '// TxCase handles Case 2: DB transaction scope anti-pattern.',
    'type TxCase struct {',
    '\tDB        *sql.DB',
    '\tDepClient *depclient.Client',
    '}',
    '',
    '// Handle serves the /cases/tx endpoint.',
    '// BASELINE (broken): Holds a database transaction open while making',
    '// a slow network call to the dep service. This causes connection pool',
    '// exhaustion under load.',
    'func (tc *TxCase) Handle(w http.ResponseWriter, r *http.Request) {',
    '\tif tc.DB == nil {',
    '\t\thttp.Error(w, "database not configured", http.StatusServiceUnavailable)',
    '\t\treturn',
    '\t}',
    '',
    '\tstart := time.Now()',
    '',
    '\t// LAB: STEP2 TODO - This is the anti-pattern: BEGIN TX, then make a',
    '\t// slow network call while holding the transaction open.',
    '\t// The fix is to:',
    '\t//   1. Move the dep call OUTSIDE the transaction',
    '\t//   2. Only use the TX for the actual DB operation',
    '\t//   3. Keep TX duration as short as possible',
    '',
    '\t// Begin transaction',
    '\ttx, err := tc.DB.Begin()',
    '\tif err != nil {',
    '\t\tlog.Printf("tx: begin error: %v", err)',
    '\t\thttp.Error(w, "tx begin failed", http.StatusInternalServerError)',
    '\t\treturn',
    '\t}',
    '\tdefer tx.Rollback()',
    '',
    '\t// LAB: STEP2 TODO - Lock a row inside the transaction.',
    '\t// This SELECT FOR UPDATE holds a row lock for the entire TX duration.',
    '\tvar balance int',
    '\terr = tx.QueryRow("SELECT balance FROM accounts WHERE name = $1 FOR UPDATE", "alice").Scan(&balance)',
    '\tif err != nil {',
    '\t\tlog.Printf("tx: query error: %v", err)',
    '\t\thttp.Error(w, "query failed: "+err.Error(), http.StatusInternalServerError)',
    '\t\treturn',
    '\t}',
    '',
    '\t// LAB: STEP2 TODO - Making a network call INSIDE the transaction.',
    '\t// This is the anti-pattern! The dep call takes ~2s, and during that',
    '\t// time we hold a DB connection AND a row lock.',
    '\t_, depErr := depclient.Call(r.Context(), tc.DepClient, "2s", "0.0")',
    '\tif depErr != nil {',
    '\t\tlog.Printf("tx: dep call error: %v", depErr)',
    '\t}',
    '',
    '\t// Update the row',
    '\t_, err = tx.Exec("UPDATE accounts SET balance = balance - 1, updated_at = NOW() WHERE name = $1", "alice")',
    '\tif err != nil {',
    '\t\tlog.Printf("tx: update error: %v", err)',
    '\t\thttp.Error(w, "update failed", http.StatusInternalServerError)',
    '\t\treturn',
    '\t}',
    '',
    '\t// Commit',
    '\tif err := tx.Commit(); err != nil {',
    '\t\tlog.Printf("tx: commit error: %v", err)',
    '\t\thttp.Error(w, "commit failed", http.StatusInternalServerError)',
    '\t\treturn',
    '\t}',
    '',
    '\telapsed := time.Since(start)',
    '\tw.Header().Set("Content-Type", "application/json")',
    '\tjson.NewEncoder(w).Encode(map[string]interface{}{',
    '\t\t"status":     "ok",',
    '\t\t"balance":    balance,',
    '\t\t"elapsed_ms": elapsed.Milliseconds(),',
    '\t})',
    '}',
    '',
])

# autoscale_case.go
write_file("pkg/cases/autoscale_case.go", [
    'package cases',
    '',
    'import (',
    '\t"crypto/sha256"',
    '\t"encoding/json"',
    '\t"fmt"',
    '\t"net/http"',
    '\t"time"',
    ')',
    '',
    '// AutoscaleCase handles Case 4: CPU-bound work for HPA testing.',
    'type AutoscaleCase struct{}',
    '',
    '// Handle serves the /cases/autoscale endpoint.',
    '// Generates CPU load that should trigger HPA scaling.',
    'func (ac *AutoscaleCase) Handle(w http.ResponseWriter, r *http.Request) {',
    '\tstart := time.Now()',
    '',
    '\t// CPU-intensive work: repeated SHA-256 hashing',
    '\tdata := []byte("workshop-autoscale-seed")',
    '\tfor i := 0; i < 100000; i++ {',
    '\t\th := sha256.Sum256(data)',
    '\t\tdata = h[:]',
    '\t}',
    '',
    '\telapsed := time.Since(start)',
    '\tw.Header().Set("Content-Type", "application/json")',
    '\tjson.NewEncoder(w).Encode(map[string]interface{}{',
    '\t\t"status":     "ok",',
    '\t\t"hash":       fmt.Sprintf("%x", data[:8]),',
    '\t\t"elapsed_ms": elapsed.Milliseconds(),',
    '\t})',
    '}',
    '',
])

print("All case files generated.")
